# Generated by Django 5.2.6 on 2025-11-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('attendence', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
